apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - blueprint-postgres.yaml
  - blueprint-mysql.yaml
  - blueprint-mongodb.yaml
  - blueprint-sqlite.yaml
  - blueprint-redis.yaml
  - blueprint-default.yaml
